apiVersion: archon.kubeup.com/v1
kind: InstanceGroup
metadata:
  name: k8s-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-node
  template:
    metadata:
      labels:
        app: k8s-node
    spec:
      networkName: k8s-net
      instanceType: t2.small
      os: CentOS
      image: ami-af4333cf
      files:
      - name: yum-repos
        path: "/config/yum_repos"
        content: |-
          kubernetes:
            name: Kubernetes
            baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
            enabled: true
            gpgcheck: true
            gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      - name: packages
        path: "/config/packages"
        content: |-
          - docker
          - kubelet
          - kubeadm
          - kubernetes-cni
      - name: setenforce
        path: "/config/runcmd/setenforce"
        template: |-
          - setenforce
          - "0"
      - name: enable-docker
        path: "/config/runcmd/enable-docker"
        template: |-
          - systemctl
          - enable
          - docker
      - name: start-docker
        path: "/config/runcmd/start-docker"
        template: |-
          - systemctl
          - start
          - docker
      - name: enable-kubelet
        path: "/config/runcmd/enable-kubelet"
        template: |-
          - systemctl
          - enable
          - kubelet
      - name: start-kubelet
        path: "/config/runcmd/start-kubelet"
        template: |-
          - systemctl
          - start
          - kubelet
      - name: kubeadm
        path: "/config/runcmd/kubeadm"
        template: |-
          - kubeadm
          - join
          - --token
          - {{ index .Configs "k8s" "token" }}
          - {{ index .Configs "k8s" "master-ip" }}
      configs:
      - name: k8s
        data:
          master-ip: MASTER_IP
          token: TOKEN
      users:
      - name: centos
