apiVersion: v1
kind: Secret
metadata:
  annotations:
    archon.kubeup.com/alias: kubelet
    archon.kubeup.com/csr: |-
      {
        "CN": "kubelet",
        "hosts": [
          "*.us-west-1.compute.internal"
        ],
        "key": {
          "algo": "ecdsa",
          "size": 256
        },
        "names": [
          {
            "O": "system:masters",
            "C": "US",
            "L": "CA",
            "ST": "San Francisco"
          }
        ]
      }
    archon.kubeup.com/status: Approved
    archon.kubeup.com/type: csr
    archon.kubeup.com/ca: k8s-ca
  name: kubelet
type: Opaque
