apiVersion: v1
kind: Secret
metadata:
  annotations:
    archon.kubeup.com/alias: apiserver
    archon.kubeup.com/csr: |-
      {
        "CN": "apiserver",
        "hosts": [
          "kubernetes",
          "kubernetes.default",
          "kubernetes.default.svc",
          "kubernetes.default.svc.cluster.local",
          "*.us-west-1.elb.amazonaws.com",
          "*.us-west-1.compute.amazonaws.com",
          "127.0.0.1",
          "10.3.0.1"
        ],
        "key": {
          "algo": "ecdsa",
          "size": 256
        },
        "names": [
          {
            "C": "US",
            "L": "CA",
            "ST": "San Francisco"
          }
        ]
      }
    archon.kubeup.com/status: Approved
    archon.kubeup.com/type: csr
    archon.kubeup.com/ca: k8s-ca
  name: apiserver
type: Opaque
